// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTaskAionys.Model;

namespace TestTaskAionys.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20181028143257_editClietnTask")]
    partial class editClietnTask
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestTaskAionys.Model.Clients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TestTaskAionys.Model.ClientTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientAddress");

                    b.Property<int?>("ClientsId");

                    b.Property<string>("Description");

                    b.Property<string>("EndTime");

                    b.Property<string>("StartTime");

                    b.Property<string>("TaskName");

                    b.HasKey("Id");

                    b.HasIndex("ClientsId");

                    b.ToTable("ClientTasks");
                });

            modelBuilder.Entity("TestTaskAionys.Model.ClientTask", b =>
                {
                    b.HasOne("TestTaskAionys.Model.Clients", "Clients")
                        .WithMany("ClientTasks")
                        .HasForeignKey("ClientsId");
                });
#pragma warning restore 612, 618
        }
    }
}
